global:
  scrape_interval: 15s
  external_labels:
    cluster: demo
    namespace: demo
    __replica__: ${PODNAME} 

scrape_configs:
- job_name: promtheus
  static_configs:
    - targets: ["prometheus:9090"]

remote_write:
- url: https://io.telemetrytower.com/api/v1/push
  authorization:
    credentials: xxx
  send_exemplars: true