global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "myservice"
    static_configs:
      - targets: ["myservice:8080"]

remote_write:
- url: https://io.telemetrytower.com/api/v1/push
  authorization:
    credentials: token
  send_exemplars: true