apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://io.telemetrytower.com/prometheus
    version: 1
    editable: true
    isDefault: true
    jsonData: 
      httpHeaderName1: Authorization
    secureJsonData: 
      httpHeaderValue1: token
  
  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: https://io.telemetrytower.com
    version: 2
    editable: true
    jsonData: 
      httpHeaderName1: Authorization
    secureJsonData: 
      httpHeaderValue1: token

